CC=gcc
CFLAGS=-g -std=c11 -pedantic -Wall -Wextra

all: htab_bucket_count.c htab_clear.c htab_erase.c htab_free.c htab_hash_function.c htab_init.c htab_insert.c htab_item_init.c htab_resize.c htab_size.c htab_find.c htab_lookup_add.c htab_for_each.c testing.c
	$(CC) $(CFLAGS) htab_bucket_count.c htab_clear.c htab_erase.c htab_free.c htab_hash_function.c htab_init.c htab_insert.c htab_item_init.c htab_resize.c htab_size.c htab_find.c htab_lookup_add.c htab_for_each.c testing.c -o testing